/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#fff8f7",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#FBF8F2",
        "on-secondary": "#ffffff",
        "surface-bright": "#FFFFFF",
        "on-surface-variant": "#574142",
        "surface-container-high": "#ffe1e1",
        "primary-fixed-dim": "#FFB3B9",
        "tertiary-container": "#721925",
        "on-secondary-fixed-variant": "#5d4200",
        "on-tertiary-fixed": "#40000c",
        "on-background": "#2a1617",
        "tertiary-fixed": "#ffdada",
        "secondary-container": "#996F04",
        "primary-fixed": "#FFD9DC",
        "surface-container-highest": "#E7DDCC",
        "inverse-surface": "#261416",
        "primary-container": "#781523",
        "on-primary-fixed": "#3B000B",
        "surface-variant": "#F2E8DC",
        "surface-container": "#F6F0E6",
        "secondary-fixed": "#ffdea6",
        "inverse-primary": "#ffb3b4",
        "secondary-fixed-dim": "#f7bd48",
        "inverse-on-surface": "#FDF7F5",
        "on-error-container": "#93000a",
        "on-secondary-container": "#715000",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#781523",
        "surface": "#FFFDF9",
        "tertiary-fixed-dim": "#ffb3b5",
        "on-tertiary-container": "#ff818a",
        "surface-dim": "#f6d1d2",
        "tertiary": "#560013",
        "outline-variant": "#ddc0bf",
        "surface-tint": "#781523",
        "outline": "#8D7B7B",
        "error": "#BA1A1A",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#241A00",
        "secondary": "#7b5800",
        "on-surface": "#2a1617",
        "on-primary": "#ffffff",
        "on-primary-container": "#ff8288",
        "on-tertiary-fixed-variant": "#871e2d",
        "error-container": "#ffdad6",
        "primary": "#570011"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "margin-sm": "1rem",
        "gutter-sm": "1rem",
        "margin": "1.5rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
        "margin-lg": "3rem",
        "gutter-lg": "2rem"
      },
      fontFamily: {
        "display-hero": ["Rozha One", "Noto Serif Devanagari", "Playfair Display", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Noto Serif Devanagari", "Playfair Display", "serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Rozha One", "Noto Serif Devanagari", "Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Noto Serif Devanagari", "Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Noto Serif Devanagari", "Playfair Display", "serif"],
        "headline-md": ["Noto Serif Devanagari", "Playfair Display", "serif"]
      },
      fontSize: {
        "display-hero": ["54px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "fontWeight": "600" }],
        "title-md": ["18px", { "lineHeight": "26px", "fontWeight": "600" }],
        "display-hero-mobile": ["34px", { "lineHeight": "42px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["38px", { "lineHeight": "46px", "fontWeight": "600" }],
        "body-lg": ["17px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
